// Generated by Wrangler
// After adding bindings to `wrangler.jsonc` or environment variables, regenerate using `wrangler types`
interface Env {
	PUBLIC_SUPABASE_URL?: string;
	PUBLIC_SUPABASE_ANON_KEY?: string;
}
